/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useMemo } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three/examples/jsm/utils/SkeletonUtils'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Dolphin2.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions['Action.001'].play()
    actions['Action.001'].setDuration(2)
    group.current.position.z = props.pos[2]
    group.current.position.x = props.pos[0]
  })
  const clonedScene = useMemo(() => {
    return SkeletonUtils.clone(nodes)
  }, [nodes])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Armature'>
          <primitive object={clonedScene.MAIN} />
          <group name='Mesh'>
            <skinnedMesh
              name='Circle002'
              geometry={clonedScene.Circle002.geometry}
              material={materials['Dolphin Body']}
              skeleton={clonedScene.Circle002.skeleton}
            />
            <skinnedMesh
              name='Circle002_1'
              geometry={clonedScene.Circle002_1.geometry}
              material={materials['Dolphin Eyes']}
              skeleton={clonedScene.Circle002_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Dolphin2.glb')
